pipeline {
    agent any

    stages {
        stage('Maven Package') {
            agent {
                docker {
                    image 'maven:3.9-amazoncorretto-21'
                    // args '-v $HOME/.m2:/root/.m2:z -u root' // Pour garder le cache Maven
                    reuseNode true // Permet de partager le même workspace que l'agent Jenkins
                }
            }

            steps {
                dir('biblio-boot') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('Docker build') {
            steps {
                dir('biblio-boot') {
                    sh 'docker build -t ajc/biblio-boot .'
                }
            }
        }

        stage('Docker compose') {
            steps {
                dir('biblio-boot') {
                    sh 'docker compose up -d'
                }
            }
        }
    }
}