pipeline {
    agent any

    stages {
        stage('Maven package') {
            agent {
                docker {
                    image 'maven:3.9.11-eclipse-temurin-21'
                    args '''
                        -v $HOME/.m2:/root/.m2:z
                        -u root
                        --network devops
                    '''
                    reuseNode true // Sans ça, il y aura un 2eme workspace
                }
            }

            steps {
                dir('projetBiblio/biblio-quarkus') {
                    withSonarQubeEnv('sonar-id') {
                        sh "mvn clean verify sonar:sonar -Dsonar.projectKey=biblio-quarkus -Dsonar.projectName='biblio-quarkus'"
                    }
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('projetBiblio/biblio-quarkus') {
                    sh 'docker build -t ajc/biblio:quarkus .'
                }
            }
        }

        stage('Docker Deploy') {
            steps {
                dir('biblio') {
                    sh 'docker compose up -d --no-deps quarkus'
                }
            }
        }
    }
}